version: '3.9'

services:
  homebase.api:
    image: ${DOCKER_REGISTRY-}homebaseapi
    build:
      context: .
      dockerfile: HomeBase.Api/Dockerfile
    network_mode: bridge
    ports:
        - "80"
        - "5000:80"
    links:
        - "db"

  homebase.web:
    image: ${DOCKER_REGISTRY-}homebaseweb
    build:
      context: .
      dockerfile: HomeBase.Web/Dockerfile
    network_mode: bridge
    ports:
        - "5010:80"
    links:
        - "homebase.api"
  
  db:
    image: mongo
    volumes:
        - db-data:/data/db
    container_name: "mongo-01"
    network_mode: bridge
    ports:
        - "27017:27017"

volumes:
   db-data:
    external: true